spring:
  properties:
    hibernate:
      default_batch_fetch_size: 100

  profiles:
    include:
      - oauth
      - h2
      - data

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  file:
    name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
  level: # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.project.study: error
    com.project.study.controller: debug